Update openvpn

diff --git a/rc/openvpn b/rc/openvpn
--- a/rc/openvpn
+++ b/rc/openvpn
@@ -1,12 +1,20 @@
  VNAME="Enigma2 OpenVPN"
   VINFO="Enigma2 OpenVPN v1"
-  BINARY="wg-quick"
+  BINARY=/usr/sbin/openvpn
+  CONFIG=/etc/openvpn/ovpn.conf
   case "$1" in
     start)
-    wg-quick up wg0
+    if  [ -n "$CONFIG" ]
+    then
+     $BINARY --daemon  --config $CONFIG 
+     else
+     echo "ovpn.conf not found"
+     exit 0
+       
    ;;
     stop)
-    wg-quick down wg0
+    kill `cat $PIDFILE` || true
+    rm $PIDFILE
    ;;
     restart)
     wg-quick down wg0
